export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_PENDING = "FETCH_PROJECT_PENDING";
export const FETCH_PROJECT_FAIL = "FETCH_PROJECT_FAIL";

export const FETCH_SCHOOL_PROJECT_SUCCESS = "FETCH_SCHOOL_PROJECT_SUCCESS";
export const FETCH_SCHOOL_PROJECT_PENDING = "FETCH_SCHOOL_PROJECT_PENDING";
export const FETCH_SCHOOL_PROJECT_FAIL = "FETCH_SCHOOL_PROJECT_FAIL";

export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_PENDING = "ADD_PROJECT_PENDING";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_PENDING = "DELETE_PROJECT_PENDING";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_PENDING = "UPDATE_PROJECT_PENDING";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export const FETCH_ONE_PROJECT_SUCCESS = "FETCH_ONE_PROJECT_SUCCESS";
export const FETCH_ONE_PROJECT_PENDING = "FETCH_ONE_PROJECT_PENDING";
export const FETCH_ONE_PROJECT_FAIL = "FETCH_ONE_PROJECT_FAIL";
