export const FETCH_SCHOOL_SUCCESS = "FETCH_SCHOOL_SUCCESS";
export const FETCH_SCHOOL_PENDING = "FETCH_SCHOOL_PENDING";
export const FETCH_SCHOOL_FAIL = "FETCH_SCHOOL_FAIL";

export const FETCH_ONE_SCHOOL_SUCCESS = "FETCH_ONE_SCHOOL_SUCCESS";
export const FETCH_ONE_SCHOOL_PENDING = "FETCH_ONE_SCHOOL_PENDING";
export const FETCH_ONE_SCHOOL_FAIL = "FETCH_ONE_SCHOOL_FAIL";

export const ADD_SCHOOL_SUCCESS = "ADD_SCHOOL_SUCCESS";
export const ADD_SCHOOL_PENDING = "ADD_SCHOOL_PENDING";
export const ADD_SCHOOL_FAIL = "ADD_SCHOOL_FAIL";

export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_PENDING = "DELETE_SCHOOL_PENDING";
export const DELETE_SCHOOL_FAIL = "DELETE_SCHOOL_FAIL";

export const UPDATE_SCHOOL_SUCCESS = "UPDATE_SCHOOL_SUCCESS";
export const UPDATE_SCHOOL_PENDING = "UPDATE_SCHOOL_PENDING";
export const UPDATE_SCHOOL_FAIL = "UPDATE_SCHOOL_FAIL";

export const LOGIN_SCHOOL_SUCCESS = "LOGIN_SCHOOL_SUCCESS";
export const LOGIN_SCHOOL_PENDING = "LOGIN_SCHOOL_PENDING";
export const LOGIN_SCHOOL_FAIL = "LOGIN_SCHOOL_FAIL";
