export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_PENDING = "USER_LOGIN_PENDING";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_PENDING = "USER_LOGOUT_PENDING";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_PENDING = "USER_UPDATE_PENDING";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_PENDING = "USER_FETCH_PENDING";
export const USER_FETCH_FAIL = "USER_FETCH_FAIL";
